const questionBank = {
  "Europa y América Latina": [
    { q: "¿Qué acuerdo estratégico busca conectar formalmente al bloque de la Unión Europea con el Cono Sur?", options: ["Acuerdo de Asociación UE-Mercosur", "Tratado Comercial Transatlántico (TTIP)", "Alianza del Pacífico Ampliada", "Tratado de Lisboa Extraregional"], correct: 0 },
    { q: "¿En qué ciudad se celebró la cumbre UE-CELAC de 2023 que reactivó las relaciones bilaterales de ambas regiones?", options: ["Madrid", "Bruselas", "Buenos Aires", "París"], correct: 1 },
    { q: "¿Qué instrumento financiero europeo apoya proyectos de infraestructura sostenible en América Latina bajo Global Gateway?", options: ["El fondo EFSD+", "El fondo FEDER regional", "El Fondo de Cohesión Clásico", "El Plan de Inversión Marshall"], correct: 0 },
    { q: "¿Cuál es el principal eje de cooperación ambiental actual entre la Unión Europea y América Latina?", options: ["Transición verde, descarbonización y energías limpias", "Fomento de la explotación minera pesada de carbón", "Subsidios estatales al petróleo convencional", "Desarrollo industrial de energía nuclear masiva"], correct: 0 },
    { q: "¿Qué país latinoamericano firmó el primer Acuerdo de Asociación Económica con la UE en el año 2002?", options: ["Chile", "Argentina", "Brasil", "Perú"], correct: 0 },
    { q: "¿Qué porcentaje aproximado de la Inversión Extranjera Directa (IED) histórica en América Latina proviene de la UE?", options: ["Alrededor del 10%", "Cercano al 35%", "Menos del 5%", "Más del 80%"], correct: 1 },
    { q: "¿Qué cláusula político-institucional es indispensable en los acuerdos modernos de la Unión Europea con América Latina?", options: ["Cláusula democrática y de respeto a los Derechos Humanos", "Alineación militar obligatoria automática", "Adopción obligatoria del Euro transaccional", "Apertura total de fronteras sin controles de aduana"], correct: 0 },
    { q: "¿Qué país de la Unión Europea lidera históricamente los lazos diplomáticos y de inversión directa en América Latina?", options: ["España", "Alemania", "Polonia", "Suecia"], correct: 0 },
    { q: "La iniciativa 'Global Gateway' de la UE compite geopolíticamente en América Latina principalmente contra las inversiones de:", options: ["Rusia", "La República Popular China", "Canadá", "La República de la India"], correct: 1 },
    { q: "¿Qué sector energético latinoamericano atrae mayor inversión de la UE en el marco de la transición ecológica?", options: ["Hidrógeno verde y cadena de valor del litio", "Extracción masiva de carbón térmico tradicional", "Refinerías de petróleo pesado convencional", "Redes de gasoductos fósiles transcontinentales"], correct: 0 }
  ],
  "República Popular China": [
    { q: "¿Cómo se denomina oficialmente la megaestrategia de infraestructura global lanzada por China en 2013?", options: ["La Franja y la Ruta (Belt and Road Initiative)", "Plan de Conectividad Asiática", "Consenso de Beijing de Infraestructura", "Ruta de la Seda Digital"], correct: 0 },
    { q: "¿Qué institución multilateral creó China en 2014 para financiar obras globales de forma independiente al Banco Mundial?", options: ["AIIB (Banco Asiático de Inversión en Infraestructura)", "Banco Africano de Desarrollo Integrado", "Fondo Monetario Asiático Alternativo", "Banco de la ASEAN para el Desarrollo"], correct: 0 },
    { q: "¿Cuál es el órgano de máxima toma de decisiones políticas efectivas dentro del Partido Comunista de China?", options: ["El Comité Permanente del Politburó", "La Asamblea Nacional de Delegados Ciudadanos", "El Consejo de Estado Consultivo Exterior", "La Secretaría General de Comercio Internacional"], correct: 0 },
    { q: "¿Qué concepto define la doctrina de política exterior china sobre desarrollo conjunto sin injerencia en asuntos internos?", options: ["Cooperación de Ganar-Ganar (Win-Win)", "Doctrina del Destino Manifiesto", "Pax Sinica de Hegemonía Imperial", "Principio de Alineamiento Ideológico Forzado"], correct: 0 },
    { q: "¿Qué estatus diplomático exige China reconocer internacionalmente a cualquier país que desee entablar lazos oficiales con Beijing?", options: ["El principio de 'Una Sola China'", "La soberanía compartida e independiente de Taiwán", "El estatus de socio de defensa del Indo-Pacífico", "La hegemonía absoluta del Mar del Sur de China"], correct: 0 },
    { q: "¿Cuál es la moneda de curso legal emitida por el Banco Popular de China que busca internacionalizarse globalmente?", options: ["Renminbi / Yuan", "Yen", "Won", "Ringgit"], correct: 0 },
    { q: "¿Qué región portuaria del sur conecta Hong Kong, Macao y Guangdong en un hub tecnológico masivo?", options: ["La Gran Bahía (Greater Bay Area)", "El Delta del Río Amarillo del Norte", "La Zona de Libre Comercio de Shanghái", "El Corredor Económico de Hainan"], correct: 0 },
    { q: "¿Qué nombre recibe el plan estratégico industrial de Beijing para liderar la alta tecnología global e inteligencia artificial?", options: ["Made in China 2025", "China Tech 2030", "Plan de Modernización del Sur Global", "Salto Tecnológico Chino Compartido"], correct: 0 },
    { q: "¿Cuál es el principal socio comercial e inversor energético de China en la región de América del Sur?", options: ["Brasil", "Ecuador", "Paraguay", "Bolivia"], correct: 0 },
    { q: "¿Qué estatus económico otorgado por la OMC disputó China intensamente a nivel global tras cumplir 15 años de su ingreso?", options: ["Economía de Mercado", "País en Desarrollo Protegido", "Nación de Tránsito Marítimo Libre", "Exportador Agrícola Primario Exclusivo"], correct: 0 }
  ],
  "La República Italiana": [
    { q: "¿Cuál es el ordenamiento institucional del Estado italiano establecido en su Constitución de 1948?", options: ["República Parlamentaria", "Monarquía Constitucional", "República Federal Presidencialista", "Estado Unitario Semipresidencialista"], correct: 0 },
    { q: "En la estructura política de la República Italiana, ¿quién ejerce la Jefatura del Gobierno?", options: ["El Presidente del Consejo de Ministros", "El Presidente de la República", "El Canciller de Asuntos Exteriores", "El Gobernador de la Banca d'Italia"], correct: 0 },
    { q: "¿Qué palacio histórico de Roma funciona como la sede oficial de la Jefatura del Estado italiano?", options: ["Palacio del Quirinal", "Palacio Chigi", "Palacio Madama", "Palacio Montecitorio"], correct: 0 },
    { q: "¿Qué acuerdos de 1929 dieron origen a la Ciudad del Vaticano y regularon las relaciones entre Italia y la Santa Sede?", options: ["Pactos de Letrán", "Tratados de Roma", "Acuerdos de Milán", "Concordato de Florencia"], correct: 0 },
    { q: "¿En qué ciudad italiana se firmaron en 1957 los tratados constitutivos de la Comunidad Económica Europea (CEE)?", options: ["Roma", "Milán", "Turín", "Venecia"], correct: 0 },
    { q: "¿Qué sector industrial define primordialmente el núcleo exportador del norte de Italia?", options: ["Diseño, moda, industria automotriz y maquinaria de precisión", "Minería a cielo abierto de carbón y siderurgia pesada", "Extracción masiva de hidrocarburos convencionales fósiles", "Desarrollo exclusivo de software de defensa militar"], correct: 0 },
    { q: "¿Cómo se denomina la histórica brecha socioeconómica entre el norte industrializado de Italia y el sur agrícola?", options: ["La cuestión del Mezzogiorno", "La fractura geopolítica alpina", "La división administrativa de Lombardía", "El dilema comercial del Mar Adriático"], correct: 0 },
    { q: "¿Cuál es la cámara parlamentaria encargada de representar a las regiones en el poder legislativo italiano?", options: ["El Senado de la República", "La Cámara de Diputados", "El Consejo de Estado", "La Asamblea Federal de Gobernadores"], correct: 0 },
    { q: "¿Qué plan de financiamiento europeo post-pandemia gestiona Italia para reestructurar su economía y transición digital?", options: ["PNRR (Plan Nacional de Recuperación y Resiliencia)", "Fondo de Cohesión Estructural Mediterráneo", "Plan de Inversión Marshall de la Eurozona", "Fondo Alianza Italia Viva 2026"], correct: 0 },
    { q: "La región del norte de Italia que tiene a Milán como capital y aporta la mayor cuota al PBI manufacturero nacional es:", options: ["Lombardía", "Sicilia", "Toscana", "Piamonte"], correct: 0 }
  ],
  "La Era de los Regionalismos": [
    { q: "¿Qué término describe un orden global caracterizado por múltiples bloques de poder regional sin una hegemonía única?", options: ["Multipolaridad", "Bipolaridad rígida ideológica", "Unilateralismo coordinado", "Globalización asimétrica aislada"], correct: 0 },
    { q: "¿Qué organización regional del sudeste asiático es considerada un modelo de integración pacífica y económica regional?", options: ["ASEAN", "MERCOSUR", "Unión Africana", "SADC"], correct: 0 },
    { q: "¿Qué tratado internacional transformó formalmente a la Comunidad Europea en la Unión Europea en 1993?", options: ["Tratado de Maastricht", "Tratado de Ámsterdam", "Tratado de Niza", "Tratado de Roma de Integración"], correct: 0 },
    { q: "¿Cómo se define el fenómeno donde los Estados delegan parte de sus competencias a instituciones comunitarias superiores?", options: ["Supranacionalidad", "Intergubernamentalismo liberal", "Federalismo descentralizado", "Secesión soberana concertada"], correct: 0 },
    { q: "El bloque regional del MERCOSUR fue fundado formalmente en 1991 mediante la firma del Tratado de:", options: ["Asunción", "Montevideo", "Brasilia", "Buenos Aires"], correct: 0 },
    { q: "¿Cuál es la principal característica de un Mercado Común frente a una Unión Aduanera?", options: ["Incluye la libre circulación de factores como capital y trabajo", "No posee un arancel externo común frente a terceros países", "Elimina de forma total las fronteras político-territoriales", "Requiere obligatoriamente la adopción de una moneda única"], correct: 0 },
    { q: "¿Qué concepto acuñado por Joseph Nye describe la capacidad de influir internacionalmente a través de cultura y valores?", options: ["Poder Blando (Soft Power)", "Poder Duro (Hard Power)", "Poder Inteligente Coercitivo", "Diplomacia Sancionatoria de Bloque"], correct: 0 },
    { q: "¿Qué acuerdo comercial de América del Norte fue renegociado y reemplazado en 2020 por el actual T-MEC?", options: ["TLCAN / NAFTA", "ALCA / FTAA", "CAFTA", "Tratado del Atlántico Norte Comercial"], correct: 0 },
    { q: "¿Qué histórica crisis institucional de desintegración regional europea culminó con el retiro formal de un Estado miembro?", options: ["El Brexit", "La crisis de deuda del Euro", "La crisis migratoria del Mediterráneo", "La reforma constitucional de Lisboa"], correct: 0 },
    { q: "¿Qué teoría sostiene que la cooperación técnica en un sector integrado genera un efecto derrame hacia otros campos?", options: ["Neofuncionalismo", "Intergubernamentalismo realista", "Estructuralismo de dependencia", "Constructivismo identitario"], correct: 0 }
  ],
  "República de la India": [
    { q: "¿De qué foro estratégico del Indopacífico forma parte la India junto con EE.UU., Japón y Australia?", options: ["El Quad (Quadrilateral Security Dialogue)", "AUKUS", "ASEAN +3 de Comercio", "Organización del Tratado del Atlántico Norte"], correct: 0 },
    { q: "¿Qué histórica región fronteriza mantiene una disputa geopolítica y militar latente entre la India y Pakistán?", options: ["Cachemira", "Tíbet", "Panyab", "Sind"], correct: 0 },
    { q: "¿Cuál es la gran estrategia de desarrollo industrial e innovación impulsada por Nueva Delhi para atraer manufacturas globales?", options: ["Make in India", "Digital India Hub", "Vibrant India Global", "India Tech 2030 Gateway"], correct: 0 },
    { q: "¿Cuál es la actual capital federal y centro administrativo de la República de la India?", options: ["Nueva Delhi", "Bombay / Mumbai", "Calcuta", "Bangalore"], correct: 0 },
    { q: "¿Qué importante foro geopolítico y económico global presidió la India durante el año 2023?", options: ["El G20", "El G7 de potencias occidentales", "La Unión de Naciones Asiáticas", "El Foro de Cooperación Económica del Caspio"], correct: 0 },
    { q: "¿Qué ciudad de la India es mundialmente reconocida como el hub tecnológico del software de exportación?", options: ["Bangalore / Bengaluru", "Nueva Delhi", "Madrás", "Jaipur"], correct: 0 },
    { q: "¿Cuál fue el principio histórico de política exterior adoptado por la India de Nehru en el marco de la Guerra Fría?", options: ["El No Alineamiento", "La Doctrina de Contención Militar", "El Alineamiento Bilateral Rígido con bloques", "El Panamericanismo Estratégico"], correct: 0 },
    { q: "¿Qué espacio oceánico es considerado por la doctrina de Nueva Delhi como su zona de seguridad prioritaria?", options: ["Océano Índico", "Océano Pacífico Occidental", "Mar de China Meridional", "Océano Atlántico Sur"], correct: 0 },
    { q: "¿Qué país mantiene una disputa fronteriza con la India en el Himalaya en la zona de la Línea de Control Actual (LAC)?", options: ["China", "Rusia", "Afganistán", "Irán"], correct: 0 },
    { q: "¿Qué alianza para mitigar el cambio climático fue fundada conjuntamente por India y Francia en la COP21?", options: ["Alianza Solar Internacional (ISA)", "Consorcio Eólico Global del Sur", "Fondo del Hidrógeno Verde Asiático", "Red Global de Biomasa Renovable"], correct: 0 }
  ],
  "África: Dinámicas Regionales": [
    { q: "¿Dónde se encuentra la sede central de la Unión Africana (UA), el organismo de integración más importante del continente?", options: ["Adís Abeba, Etiopía", "El Cairo, Egipto", "Nairobi, Kenia", "Johannesburgo, Sudáfrica"], correct: 0 },
    { q: "¿Qué siglas identifican al acuerdo de libre comercio continental africano operativo desde 2019?", options: ["AfCFTA", "ECOWAS", "SADC", "COMESA"], correct: 0 },
    { q: "¿Qué comunidad económica regional de África lidera las mediaciones políticas y de seguridad en el oeste del continente?", options: ["ECOWAS / CEDEAO", "SADC del Sur", "EAC de África Oriental", "Unión del Magreb Árabe"], correct: 0 },
    { q: "¿Qué recurso mineral estratégico para la transición tecnológica concentra la República Democrática del Congo?", options: ["Cobalto y Coltán", "Petróleo de esquisto liviano", "Litio de salar andino", "Hierro magnético pesado"], correct: 0 },
    { q: "¿Qué potencia económica de África forma parte del bloque geoestratégico BRICS desde el año 2010?", options: ["Sudáfrica", "Nigeria", "Kenia", "Angola"], correct: 0 },
    { q: "¿Qué país del norte de África mantiene una fuerte tensión con Etiopía por la Gran Presa del Renacimiento?", options: ["Egipto", "Argelia", "Marruecos", "Túnez"], correct: 0 },
    { q: "¿Qué franja geográfica africana semiárida enfrenta graves crisis de seguridad e insurgencia en los últimos años?", options: ["El Sahel", "El Cuerno de África", "El Valle del Rift Oriental", "La Cuenca del Kalahari"], correct: 0 },
    { q: "¿Cuál es el principal socio bilateral del continente africano en términos de financiamiento y construcción de infraestructuras?", options: ["La República Popular China", "Estados Unidos", "Francia", "El Reino Unido"], correct: 0 },
    { q: "¿Qué país de África Occidental posee la mayor población del continente y es una de sus principales potencias petroleras?", options: ["Nigeria", "Sudáfrica", "Etiopía", "Ghana"], correct: 0 },
    { q: "¿Qué misión de paz africana fue desplegada bajo mandato multilateral para combatir la insurgencia y estabilizar Somalia?", options: ["AMISOM / ATMIS", "MINUSMA en Mali", "MONUSCO en el Congo", "UNMISS en Sudán"], correct: 0 }
  ],
  "Hegemonía en Juego (EE.UU.)": [
    { q: "La arquitectura constitucional de EE.UU. establece que el Presidente es electo de forma indirecta por:", options: ["El Colegio Electoral", "Voto popular directo unificado nacional", "La Cámara de Representantes federal", "El Senado de la Nación"], correct: 0 },
    { q: "¿Cuántos miembros componen en su totalidad el Colegio Electoral de los Estados Unidos de América?", options: ["538 electores", "435 representantes", "100 senadores", "270 delegados"], correct: 0 },
    { q: "¿Qué número mínimo de votos electorales se requiere para ganar la presidencia de EE.UU.?", options: ["260 votos", "270 votos", "300 votos", "435 votos"], correct: 1 },
    { q: "¿Cómo se denominan los estados clave de EE.UU. que no tienen una tendencia partidaria fija?", options: ["Swing States / Estados péndulo", "Red States conservadores", "Blue States demócratas", "Territorios Incorporados No Estatales"], correct: 0 },
    { q: "¿Qué estado norteamericano aporta el mayor número de votos electorales por su peso demográfico?", options: ["California", "Texas", "Nueva York", "Florida"], correct: 0 },
    { q: "¿Qué cuerpo del Poder Legislativo estadounidense posee la atribución exclusiva de ratificar los tratados internacionales?", options: ["El Senado", "La Cámara de Representantes", "La Corte Suprema de Justicia", "El Departamento de Estado Ejecutivo"], correct: 0 },
    { q: "¿Qué histórica doctrina del siglo XIX sintetizaba la postura geopolítica de Washington como 'América para los americanos'?", options: ["Doctrina Monroe", "Doctrina Truman de contención", "Estrategia del Plan Marshall", "Doctrina del Destino Manifiesto"], correct: 0 },
    { q: "¿Cuál es el principal órgano encargado de coordinar la política exterior y de defensa en la Casa Blanca?", options: ["El Consejo de Seguridad Nacional (NSC)", "El Departamento de Comercio Exterior", "La Oficina de Inteligencia Logística", "El Comité de Asuntos Judiciales del Capitolio"], correct: 0 },
    { q: "¿Qué ley faculta al Congreso de EE.UU. a limitar la capacidad del Presidente de mantener tropas en el exterior?", options: ["Ley de Poderes de Guerra (War Powers Resolution)", "Ley de Seguridad Nacional de 1947", "Acta Patriótica Antiterrorista", "Enmienda Platt de Intervención Regional"], correct: 0 },
    { q: "El máximo tribunal de revisión constitucional de EE.UU. está compuesto por:", options: ["9 jueces con cargo vitalicio", "7 jueces de designación bianual", "12 jueces de elección popular directa", "15 magistrados de carrera federal"], correct: 0 }
  ],
  "Diplomacia y Cooperación": [
    { q: "¿Qué principio del Derecho Internacional consagra el Artículo 2(7) de la Carta de la ONU para proteger la soberanía estatal?", options: ["Principio de No Injerencia en asuntos internos", "Derecho de Veto Absoluto incondicional", "Jurisdicción Universal Compulsiva", "Principio de Autodeterminación Comercial Libre"], correct: 0 },
    { q: "¿Qué convención internacional de 1961 codificó los privilegios, funciones e inmunidades de las misiones diplomáticas?", options: ["Convención de Viena sobre Relaciones Diplomáticas", "Tratado de Paz de Westfalia", "Acuerdo de Ginebra Humanitario", "Protocolo de San José sobre Derechos Civiles"], correct: 0 },
    { q: "¿Qué órgano de las Naciones Unidas posee la competencia exclusiva de emitir resoluciones de cumplimiento obligatorio?", options: ["El Consejo de Seguridad", "La Asamblea General Consultiva", "La Corte Internacional de Justicia", "El Consejo Económico y Social"], correct: 0 },
    { q: "¿Cuáles son los cinco Estados soberanos con asiento permanente y derecho de veto en el Consejo de Seguridad de la ONU?", options: ["EE.UU., Rusia, China, Francia y el Reino Unido", "EE.UU., Alemania, Japón, China y Rusia", "EE.UU., Reino Unido, India, China y Brasil", "Rusia, China, India, Brasil y Sudáfrica"], correct: 0 },
    { q: "¿En qué ciudad europea se encuentra la sede oficial de la Corte Internacional de Justicia (CIJ)?", options: ["La Haya, Países Bajos", "Ginebra, Suiza", "Nueva York, Estados Unidos", "Estrasburgo, Francia"], correct: 0 },
    { q: "¿Cómo se denomina la modalidad de cooperación internacional realizada de forma conjunta entre dos países en desarrollo?", options: ["Cooperación Sur-Sur", "Cooperación Triangular de Gestión", "Cooperación Norte-Sur Horizontal", "Asistencia Multilateral para el Desarrollo"], correct: 0 },
    { q: "¿Qué programa del sistema de la ONU coordina la agenda global de desarrollo social y humano?", options: ["PNUD", "ACNUR para Refugiados", "Organización Mundial del Comercio", "Fondo Monetario Internacional"], correct: 0 },
    { q: "¿Cuál es la principal característica de la diplomacia multilateral frente a la bilateral tradicional?", options: ["Involucra la participación concertada de tres o más Estados u organismos", "Requiere indispensablemente la mediación oficial del Vaticano", "Solo se ejerce de manera legítima en tiempos de guerra declarada", "No utiliza agentes diplomáticos formalmente acreditados"], correct: 0 },
    { q: "¿Qué concepto define a la misión diplomática permanente de máxima jerarquía enviada por un Estado ante un tercer Estado?", options: ["Embajada", "Consulado General de Distrito", "Delegación Comercial Temporal de Frontera", "Cancillería Administrativa Concurrente"], correct: 0 },
    { q: "¿Qué foro internacional coordina y evalúa las directrices globales sobre Ayuda Oficial al Desarrollo (AOD)?", options: ["El CAD de la OCDE", "El Banco Internacional de Desarrollo", "El Grupo del G77 + China", "La Conferencia de las Partes de Bonn"], correct: 0 }
  ],
  "Medio Oriente hasta el Pacífico": [
    { q: "¿Qué estratégico estrecho marítimo concentra la mayor circulación comercial y de hidrocarburos hacia Asia Oriental?", options: ["Estrecho de Malaca", "Estrecho de Ormuz", "Canal de Suez", "Estrecho de Bab el-Mandeb"], correct: 0 },
    { q: "¿Qué estrecho marino conecta el Golfo Pérsico con el Mar de Omán, siendo un cuello de botella petrolero global?", options: ["Estrecho de Ormuz", "Estrecho de Malaca", "Canal de Panamá", "Bósforo de integración regional"], correct: 0 },
    { q: "¿Qué foro multilateral de seguridad del sudeste asiático busca rebajar las tensiones regionales?", options: ["Foro Regional de la ASEAN (ARF)", "Organización de Cooperación de Shanghái", "Foro del Pacífico Sur de Naciones", "Alianza Trilateral del AUKUS"], correct: 0 },
    { q: "¿Qué nombre recibe la histórica disputa territorial marítima sobre archipiélagos que enfrenta a China con países del sudeste asiático?", options: ["Disputa de las Islas Spratly y Paracel", "Conflicto de soberanía de las Islas Kuriles", "Dilema de las Islas de la Sonda", "Crisis de las Islas de la Sociedad Pacífica"], correct: 0 },
    { q: "¿Qué alianza de defensa y seguridad estratégica fue firmada en 2021 entre Australia, Reino Unido y EE.UU.?", options: ["AUKUS", "ANZUS", "SEATO del sudeste de Asia", "Alianza de Inteligencia de los Cinco Ojos"], correct: 0 },
    { q: "¿Cuál es la península de Asia oriental dividida militar e ideológicamente por el paralelo 38 desde el siglo XX?", options: ["Península de Corea", "Península de Indochina", "Península de Malaca", "Península de Anatolia"], correct: 0 },
    { q: "¿Qué acuerdo diplomático de 2020 normalizó las relaciones de Israel con Emiratos Árabes Unidos y Baréin?", options: ["Acuerdos de Abraham", "Acuerdos de Camp David", "Tratados de Paz de Oslo", "Conferencia de Madrid sobre Medio Oriente"], correct: 0 },
    { q: "¿Qué importante economía insular y democrática autónoma es reclamada soberanamente por la República Popular China?", options: ["Taiwán", "Singapur", "Filipinas", "Sri Lanka"], correct: 0 },
    { q: "¿Qué foro de cooperación intergubernamental reúne a 21 economías de la Cuenca del Pacífico promoviendo el libre comercio?", options: ["APEC", "CPTPP", "RCEP de integración regional", "Alianza del Pacífico"], correct: 0 },
    { q: "¿Qué estrecho marítimo controla el acceso sur al Mar Rojo y al flujo comercial hacia el Canal de Suez?", options: ["Estrecho de Bab el-Mandeb", "Estrecho de Ormuz", "Estrecho de Gibraltar", "Estrecho de los Dardanelos"], correct: 0 }
  ],
  "Rusia en el Siglo XXI": [
    { q: "¿De qué importante bloque de potencias emergentes globales es miembro fundador la Federación de Rusia?", options: ["Los BRICS", "La Unión Económica Euroasiática", "La Organización de Cooperación de Shanghái", "El Grupo del G20 Emergente"], correct: 0 },
    { q: "¿Cómo se denomina la unión aduanera e integración económica regional lanzada por Moscú en el año 2015?", options: ["Unión Económica Euroasiática (UEE)", "Comunidad de Estados Independientes (CEI)", "Alianza del Pacto de Varsovia Renovado", "Bloque del Caspio de Cooperación"], correct: 0 },
    { q: "¿Qué alianza de seguridad político-militar colectiva lidera Rusia junto con varias exrepúblicas soviéticas?", options: ["ODKB / OTSC", "Organización de Cooperación de Shanghái", "Pacto Multilateral de Tashkent", "Alianza Euroasiática de Minsk"], correct: 0 },
    { q: "¿Qué gigante corporación energética controlada por el Estado ruso monopoliza la exportación de gas natural?", options: ["Gazprom", "Rosneft", "Lukoil", "Novatek"], correct: 0 },
    { q: "¿Qué estratégica península de Europa oriental fue anexada por la Federación de Rusia en el año 2014?", options: ["Crimea", "Kamchatka", "Kola", "Peloponeso"], correct: 0 },
    { q: "¿Qué enclave portuario ruso militarizado con acceso al Mar Báltico se encuentra geográficamente aislado del resto del país?", options: ["Kaliningrado", "San Petersburgo", "Vladivostok", "Murmansk"], correct: 0 },
    { q: "¿Cuál es la doctrina geopolítica exterior rusa que prioriza la integración continental frente a la influencia occidental?", options: ["Euroasiatismo", "Atlantismo Liberal", "Paneslavismo Ortodoxo Aislado", "Doctrina del Espacio Ruso Único"], correct: 0 },
    { q: "En su estrategia en Medio Oriente, ¿cuál ha sido el principal aliado estatal de Moscú con bases militares permanentes?", options: ["Siria", "Irán", "Irak", "Egipto"], correct: 0 },
    { q: "¿Qué importante ruta marítima ártica está priorizando desarrollar Rusia ante el cambio climático?", options: ["La Ruta Marítima del Norte (NSR)", "El Paso del Noroeste Canadiense", "El Corredor del Volga-Don", "El Canal de Navegación del Obi"], correct: 0 },
    { q: "¿Qué tratado de desarme y control de armas nucleares con EE.UU. fue suspendido formalmente por Rusia en 2023?", options: ["Nuevo START", "Tratado INF de fuerzas intermedias", "Tratado ABM de antimisiles", "Acuerdo SALT II de limitaciones"], correct: 0 }
  ]
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { questionBank };
}
